import type { Metadata } from 'next';
import './globals.css';
import { Public_Sans } from 'next/font/google';

const public_sans = Public_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Memory Card',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${public_sans.className} antialiased`}>{children}</body>
    </html>
  );
}
